### ISSUE TITLE
Window/level presets to choose from

### ISSUE THREAD

**Issue by sankhesh** [Kitware/VolView#181]
It would be awesome to have different window/level presets based on different percentiles of the data scalar distribution.
A really sweet deal would be if there were thumbnails to go with them just like color function thumbnails.

**Comment by aylward** [comment]
For CT there are pre-defined window/level values - we should add those.

We should also read and use the DICOM tags for suggested W/L setting.

Extension of #6

**Comment by aylward** [comment]
Presets should include 0-50th percentile, 30-70th, ...

**Comment by aylward** [comment]
See also #270
