### ISSUE TITLE
Cutting into objects causes them to have a dark appearance

### ISSUE THREAD

**Issue by aylward** [Kitware/VolView#245]
![image](https://user-images.githubusercontent.com/279727/201799951-6a87d1ea-20c8-47ad-b80c-89ef68652a73.png)

In the above figure, the bone take a dark hue where it is cut by the crop tool.  This happens on every CT dataset and anonymous data tried, for every rendering preset, and all types of rendering EXCEPT Hybrid rendering with the blending at 1.0 (far right) or with Ambient lighting at max.

**Comment by floryst** [comment]
Something to look into: whether lighting is done before or after the cropping planes are applied.

**Comment by aylward** [comment]
@sankhesh
