### ISSUE TITLE
LAO slides have no effect on image quality

### ISSUE THREAD

**Issue by aylward** [Kitware/VolView#248]
Changing the slide has no noticeable effect on the rendering quality or speed.

Also, sometimes moving one slider causes the other to move into unpredictable new values.

**Comment by aylward** [comment]
@aylward - verify on volview-dev.kitware.app

**Comment by sankhesh** [comment]
@aylward There are no LAO sliders on the app anymore.

**Comment by aylward** [comment]
:)

And the Scatter Blending slider seems to work as expected.
