### ISSUE TITLE
build error with no matching constructor for initialization of 'itk::wasm::Pipeline'

### ISSUE THREAD

**Issue by lxmedai** [Kitware/VolView#299]
I try to build the project using the command 'npm run build:all' and get the errors pointing to the argument mismatching for the itk::wasm::Pipeline:
/work/dicom.cpp:309:23: error: no matching constructor for initialization of 'itk::wasm::Pipeline'
  itk::wasm::Pipeline pipeline("DICOM-VolView", "VolView pipeline to access DICOM data", argc,
                      ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/ITKWebAssemblyInterface/include/itkPipeline.h:105:5: note: candidate constructor not viable: requires 3 arguments, but 4 were provided
    Pipeline(std::string description, int argc, char **argv);
    ^
/ITKWebAssemblyInterface/include/itkPipeline.h:108:5: note: candidate constructor not viable: requires 2 arguments, but 4 were provided
    Pipeline(int argc, char **argv)
    ^
/ITKWebAssemblyInterface/include/itkPipeline.h:101:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
class Pipeline: public CLI::App
      ^
I can provide the full error messages printed on the terminal if needed. Thanks in advance for your kind help!

**Comment by floryst** [comment]
Have you updated your itk-wasm docker image? My first guess is that it's out of date. Check the output of `docker images`.

**Comment by lxmedai** [comment]
Here below is the output:

REPOSITORY           TAG                 IMAGE ID       CREATED         SIZE
itkwasm/emscripten   20220706-ed04463e   b031c3e20091   9 months ago    4.21GB

**Comment by floryst** [comment]
FYI if you are just trying to get a local vanilla build of VolView, you can just run `npm run build`. The itk-wasm components are already built. You should only run `npm run build:all` if you are modifying the dicom IO components.

That being said, if you are modifying the IO components, you will need to run `docker pull itkwasm/emscripten:latest`, since your docker image is out of date.

**Comment by lxmedai** [comment]
Thanks a lot for the help and sorry that I forgot to respond to your kind reply!
