### ISSUE TITLE
Unable to load the .vti file.

### ISSUE THREAD

**Issue by YeonHoJeong** [Kitware/VolView#306]
Hello,
While expressing Volume Image through VolView, at some point, I was unable to load my .vti file.

It is normally loaded from pages using vtk.js that I made myself or from other pages provided by your company.

Can VolView no longer load .vti files?

![image](https://user-images.githubusercontent.com/14609518/232434078-2b01f07b-7c7d-4d95-8c7a-e5771de40ec5.png)
![image](https://user-images.githubusercontent.com/14609518/232434136-dd23b3c5-66e7-4ba3-a4dd-cdbfb9fb7d7f.png)

**Comment by floryst** [comment]
This is fixed in dev but not stable. I will backport the fixes to stable.

**Comment by floryst** [comment]
This is now fixed in stable (volview.netlify.app).
