### ISSUE TITLE
I have a question about DICOMIO class

### ISSUE THREAD

**Issue by YeonHoJeong** [Kitware/VolView#318]
Hello.

I'm studying the VolView project and how to actually apply vtk.js.

I have a question while trying to figure out the code.

The initialize() method is declared private, and I saw that the pina provider initialize the Service Worker by calling initialize().

The private method of DICOMIO Class was called from outside, not from inside the class, is this your intention?

**Comment by PaulHax** [comment]
Good find.  Would you like to make a PR making `initialize` public?

**Comment by floryst** [comment]
Good catch! I think I meant to remove the `private` qualifier, like Paul mentioned.

**Comment by YeonHoJeong** [comment]
@PaulHax @floryst I'm happy to finally contribute to this project! 😃
Soon, I'll give you a PR.

**Comment by floryst** [comment]
Closed as fixed (#320).
