### ISSUE TITLE
Opacity not linear / underestimated ?

### ISSUE THREAD

**Issue by salimkanoun** [Kitware/VolView#355]
Hi there,

I have a question about Opacity when fusing PET and CT images, the Opacity slider is wrong,

Here a comparison of the VolView and Fiji PET/CT Viewer in the publicly available Orthanc Dataset (https://demo.orthanc-server.com/app/explorer.html#study?uuid=6b9e19d9-62094390-5f9ddb01-4a191ae7-9766b715)

Opacity of 0.5

VolView : 
![image](https://github.com/Kitware/VolView/assets/25229822/6e43bc3e-8a1d-4c4a-bb8c-04a5083f5e45)

Fiji : 
![image](https://github.com/Kitware/VolView/assets/25229822/01d2d346-9bed-4f46-b9c8-78089350172e)

Opacity of 1 
VolView : 
![image](https://github.com/Kitware/VolView/assets/25229822/9af56914-f919-4e99-938f-1156139cc9ff)

Fiji : 
![image](https://github.com/Kitware/VolView/assets/25229822/edde6754-9905-4d3a-86f5-c08c282e3c0f)

As you can see the Opacity in VolView is much less intensity than in Fiji.
The Opacity =  1 example illustrate the most the issue, at Opacity = 1 for PET layer the CT should not be visible at all because PET hide it completly, that the behaviour in Fiji but in VolView the CT is still clearly visible.

The Opacity is time to time used by physician to switch between volume being displayed ( 0 =  only CT and 1 = only PET) and the opacity should be linear 

In Volview I have the impression the slider give a range of 0 to  0.5 opacity (or even less maybe 0 - 0.4)

Thanks for any information about that,

Best regards,

Salim

**Comment by salimkanoun** [comment]
and 80% opacity 

VolView : 
![image](https://github.com/Kitware/VolView/assets/25229822/d12f1961-9b2e-4300-87b9-26a2ab81f4d6)

Fiji : 

![image](https://github.com/Kitware/VolView/assets/25229822/ae8e5deb-35f9-4a0b-802e-537d517c6ebd)

**Comment by PaulHax** [comment]
@salimkanoun Thanks for highlighting this issue.  Besides the opacity slider, the PET layer's opacity is reduced by an opacity transfer function driven by image intensities.  

It does sound better to remove the opacity transfer function, so only the slider uniformly changes the transparency of the PET layer.

**Comment by PaulHax** [comment]
@salimkanoun Would love to get your opinion on PR #449 addressing this issue.
