### ISSUE TITLE
Fetus ultrasound does not look initially render well - level is wrong

### ISSUE THREAD

**Issue by aylward** [Kitware/VolView#371]
Initial rendering looks poor:

![image](https://github.com/Kitware/VolView/assets/279727/85b9df93-e961-4444-a8de-e65cad16a5b0)

Shifting the opacity curve fixes it:

![image](https://github.com/Kitware/VolView/assets/279727/72a90061-86fa-48ee-a97a-a19a707eabd4)

**Comment by floryst** [comment]
Related to supporting setting default presets for datasets.

**Comment by floryst** [comment]
The reason behind the bad rendering is because the sample dataset is taking the CT-AAA colormap rather than US-Fetal. We need to support setting default view config values from the sample dataset configuration.
