### ISSUE TITLE
How to import DICOM files in the project and display them in 3D?

### ISSUE THREAD

**Issue by 1413194910** [Kitware/VolView#373]
I am very interested in your project and currently trying to use it to process DICOM files and display them in 3D. In the project's documentation and code, I found some DICOM-related code snippets, but still not quite sure how to properly import DICOM files and display them as 3D models.

In the project, I found the following code snippets:

handleDicomFile() - This method seems to be used to import DICOM files, but I'm not sure about the correct usage and parameters of this method.

parseDicomData() - This method is called somewhere in the code, not sure if this method is used to parse DICOM data, and how to use it correctly.

render3DModel() - I'm guessing this method might be used to display DICOM data as a 3D model, but not sure how to properly call it and pass it the parsed DICOM data.

I've checked the project's documentation and code, but I'm still a bit confused about the correct use of the above methods and the entire implementation process. I hope you can give me some advice on the process and steps on how to correctly import DICOM files, parse the data and display it as a 3D model.

If possible, please provide some sample code or detailed instructions, it will be very helpful for me. If there are other documents or resources that can be referred to, please let me know, I will read them carefully.

Thank you so much for your time and help!

best regards,

**Comment by PaulHax** [comment]
I don't see those functions in VolView.  Wrong repo?  

Good place to get help is here: https://discourse.vtk.org/
