### ISSUE TITLE
Tools not interactive after layout switch

### ISSUE THREAD

**Issue by PaulHax** [Kitware/VolView#424]
Reproduce:
1. Load prostate
2. Draw Ruler in upper left viewport
3. Switch Layout to Axial Only
4. Switch Layout to Quad View
5. Bug: Click to drag Ruler handle. But nothing happens

### More info
After droping another tool in the same viewport, the broken tool becomes interactive again.  

WidgetRepresentations are not getting rendered after layout switches.

**Comment by floryst** [comment]
I think I know what's happening here. I'm pretty sure I fixed this in one of my unmerged widget branches.
