### ISSUE TITLE
Annotatation tools hard to see.  Increase Stroke width.

### ISSUE THREAD

**Issue by PaulHax** [Kitware/VolView#433]
It has been reported that Rectangle annotation tools are hard to see, especially with some colors.  Increasing stroke width will help.

Implimentation options:
1. Global `annotationToolStrokeWidth` value, configurable via config.json.
2. Per label `strokeWidth` config.   

Thoughts?

**Comment by floryst** [comment]
Having a global and per-tool config sounds good to me.
