### ISSUE TITLE
Controlling layer opacity needs better layer labels: which data is layer 1, 2, ...

### ISSUE THREAD

**Issue by aylward** [Kitware/VolView#462]
Layers need more specific labels in the rendering tab - otherwise it is unclear which data relates to which layer.

![image](https://github.com/Kitware/VolView/assets/279727/833c313f-ad97-47d7-9510-2afbb5235e30)

Ideas for solving this
1) Changer layer name to match data name
2)  Each time a layer is added, it is assigned a number and that number is listed on the data thumbnail next to the +/- layer icon.   That number is then used when listing layers on the rendering tab.
3) Right clicking or hovering over a name layer listed in the rendering tab causes information on that layer to appear: filename, colormap, show/hide, ...

**Comment by PaulHax** [comment]
Implemented idea 1 in #479

**Comment by PaulHax** [comment]
Layer names are matching the data browsers series data name now.

![image](https://github.com/Kitware/VolView/assets/16823231/df8f99bc-7258-42b9-84bf-70616ff4f639)
