### ISSUE TITLE
Losing labels with matching names on serialization

### ISSUE THREAD

**Issue by PaulHax** [Kitware/VolView#477]
### Steps:
1. Create 2 labels named "foo"
2. Save a session.volview.zip
3. Load volview.zip file
4. Bug: Only one label with name "foo" apears in label pallet.  Expected 2 labels named "foo".

### Approach

Support serialization of labels with same name.  Later, if we want to enforce unqiue label names, do that at GUI form level.  

Related: https://github.com/Kitware/VolView/issues/454

**Comment by floryst** [comment]
Did we discuss label name uniqueness? If we require unique labels, then we should key off the name. If not, then we should be generating UUIDs for labels.

**Comment by PaulHax** [comment]
We did not discuss, but at the moment, the tool stores don't require unique label names.  The stores generate IDs for labels. 
 However, the volview.zip JSON indexes labels by `name`.  

As an approach, suggesting to update serialziation code to store labels by ID.  If we want to enforce name uniquenss, let us do that at the app edges ("Edit Label" modal and volview.zip import)?

**Comment by PaulHax** [comment]
Turns out session.volview.zip JSON actualy indexes labels by generated ID, but `useLabels.mergeLabel` merges labels with the same name on deserialization. Opend PR changes tool stores to call `useLabels.addLabel` in deserialization.
