### ISSUE TITLE
BUG: "Open files" fails to load DICOM ZIP archives

### ISSUE THREAD

**Issue by tbirdso** [Kitware/VolView#500]
## Steps to reproduce:
1. View sample data URLs: https://github.com/Kitware/VolView/blob/main/src/config.ts#L178
2. Download `MRA-Head_and_Neck.zip`: https://data.kitware.com/api/v1/item/6352a2b311dab8142820a33b/download
3. Visit the VolView preview: https://deploy-preview-438--volview-dev.netlify.app/
4. Click "Open files" and navigate to the ZIP download

Also reproducible with other sample DICOM archive downloads from `config.ts`.

## Expected behavior: 

DICOM data loads and the MR head volume is visible in VolView

## Observed behavior: 
![image](https://github.com/Kitware/VolView/assets/40648863/c2638014-7ab0-4763-98af-7a89339b1213)

Console error:
```
Could not read the input DICOM file
o.printErr @ read-dicom-tags.umd.js:1
```

Workaround: I can drag-and-drop the zip archive on the VolView window to load. Loading by drag-and-drop succeeds, by "Open files" dialog does not.

## Versions

Latest: https://volview.kitware.app/

## Platforms

Windows 10, 11
Chrome, Firefox, Edge browsers

cc @floryst

**Comment by floryst** [comment]
@aylward @PaulHax can you try this on your machines? I can't reproduce this on a Mac (the data loads just fine).

**Comment by PaulHax** [comment]
Not reproduced.  "Open Files" dialog is working for me on Ubuntu.

**Comment by timthirion** [comment]
I was able to reproduce this on Windows with the most recent Firefox.

**Comment by aylward** [comment]
I was able to reproduce this on Windows with most recent Chrome.

**Comment by floryst** [comment]
#503 should fix this issue. Please try the deploy preview link provided in the comments in that PR.
