### ISSUE TITLE
Export segment groups 

### ISSUE THREAD

**Issue by PaulHax** [Kitware/VolView#529]
Folks are asking to download segment group images in a format of their choosing.

Suggest we add a download button here:
 
![segmentgroupdownload](https://github.com/Kitware/VolView/assets/16823231/c98d0f64-ec20-4454-a92b-8ae11b7b85b5)

That pops a modal simlar to the "Save Session" with 2 inputs: 
- filename (let filename default to segment group name)
- exported image file format (list of supported formats)

Could have some GUI to set the segment group image format in the session.volview.zip file and utilize the logic in https://github.com/Kitware/VolView/pull/527.    But perphaps a one off download button per segment group scratches the use cases.  So configuring format in session.volview.zip is only possible via config.JSON file.

**Comment by aylward** [comment]
I like it (the button, its location, and the functionality)!
