### ISSUE TITLE
如何回显dcm文件的标记

### ISSUE THREAD

**Issue by Mrchenshangfeng** [Kitware/VolView#531]
如何打开dcm文件进行标记之后，然后对标记dcm文件另存。之后打开这个另存文件，之前的标记还能回显 

![1702631912969](https://github.com/Kitware/VolView/assets/51854736/9ecba205-832b-480d-a418-f3af37a1b30f)

**Comment by PaulHax** [comment]
Painting annotions/segmentations are represetned as seperate images.  The "Save Session" button saves the base .DCM DICOM image and a seperate segmentation image.  When you open the session.volview.zip file, the painted segmentation will get automatily shown.   

With https://github.com/Kitware/VolView/pull/539 VolView can save the painted segmentation file as a seperate .DCM file.
