### ISSUE TITLE
The save dialog could have an option to choose which output format to use (from a list of supported formats) for a Segmentation

### ISSUE THREAD

**Issue by jadh4v** [Kitware/VolView#536]
Don't know if its worth it, but I think the save dialog could have an option to choose which format to use (from a list of supported formats)? Another option is to just be able to modify the default from `Settings` tab.

_Originally posted by @jadh4v in https://github.com/Kitware/VolView/pull/527#discussion_r1416593174_

**Comment by PaulHax** [comment]
Lets talk about that here: https://github.com/Kitware/VolView/issues/529
