### ISSUE TITLE
there are some problems in npm install process,I don't know how to figure it out.

### ISSUE THREAD

**Issue by XuTianHDU** [Kitware/VolView#544]
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: parallel-webpack@2.6.0
npm WARN Found: webpack@5.75.0
npm WARN node_modules/webpack
npm WARN   peer webpack@">=1.11.0" from eslint-import-resolver-webpack@0.13.2
npm WARN   node_modules/eslint-import-resolver-webpack
npm WARN     eslint-import-resolver-webpack@"^0.13.2" from @vue/eslint-config-airbnb@6.0.0
npm WARN     node_modules/@vue/eslint-config-airbnb
npm WARN   7 more (file-loader, html-webpack-plugin, kw-doc, null-loader, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer webpack@"^1.12.9 || ^2.2.0 || ^3.x || ^4.x" from parallel-webpack@2.6.0
npm WARN node_modules/parallel-webpack
npm WARN   parallel-webpack@"^2.6.0" from kw-doc@3.1.2
npm WARN   node_modules/kw-doc
npm WARN 
npm WARN Conflicting peer dependency: webpack@4.47.0
npm WARN node_modules/webpack
npm WARN   peer webpack@"^1.12.9 || ^2.2.0 || ^3.x || ^4.x" from parallel-webpack@2.6.0
npm WARN   node_modules/parallel-webpack
npm WARN     parallel-webpack@"^2.6.0" from kw-doc@3.1.2
npm WARN     node_modules/kw-doc
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@3.22.5: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /Users/xutian/.npm/_cacache/index-v5/7a/83/d6c55c3522c2134fc2a5a67e6313d21b28eaabcad6bee21066c9e46fd650
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/Users/xutian/.npm"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xutian/.npm/_logs/2024-01-26T10_17_51_348Z-debug-0.log

**Comment by floryst** [comment]
This is a problem on your system. The easiest fix is to remove the `/Users/xutian/.npm` folder on you machine and run the commands again.
