### ISSUE TITLE
Error "Failed to build volume" - on Chrome  

### ISSUE THREAD

**Issue by nUdawatte** [Kitware/VolView#571]
I encounterd an error while loading two DICOMs and then when I tried to switch to the second image. To make sure I tried the same on your online app (https://volview.kitware.app/) and the error is there as well. 

1. I uploaded one DICOM image , everything works fine 
2. Then I uploaded another DICOM image using file browse . It is visibale in the sidebar but when I clicked on it following error occurs 

**Failed to build volume
RuntimeError: Aborted(). Build with -sASSERTIONS for more info.. More details can be found in the developer's console.**

and on dev console 

```
read-image-dicom-file-series.js:8 Aborted()
Module.printErr @ read-image-dicom-file-series.js:8
abort @ read-image-dicom-file-series.js:8
_abort @ read-image-dicom-file-series.js:8
$func38 @ 0149037e:0x65df
$func3297 @ 0149037e:0x20fee1
$func518 @ 0149037e:0x39ecc
$func1692 @ 0149037e:0x106541
$func767 @ 0149037e:0x69064
$func546 @ 0149037e:0x3f2fd
$func3514 @ 0149037e:0x22fdee
$func387 @ 0149037e:0x27925
$func4045 @ 0149037e:0x26c1b8
$func2634 @ 0149037e:0x1aed94
$func3917 @ 0149037e:0x267c72
$func4049 @ 0149037e:0x26c5b0
$N @ 0149037e:0x358788
Module._main @ read-image-dicom-file-series.js:8
callMain @ read-image-dicom-file-series.js:8
OI @ c8dc6423-97ff-45e5-9b0a-41f4279efd68:5
vI @ c8dc6423-97ff-45e5-9b0a-41f4279efd68:5
runPipeline @ c8dc6423-97ff-45e5-9b0a-41f4279efd68:5
await in runPipeline (async)
I @ c8dc6423-97ff-45e5-9b0a-41f4279efd68:1
useErrorMessage.ts:13 RuntimeError: Aborted(). Build with -sASSERTIONS for more info.
    at abort (read-image-dicom-file-series.js:8:6226)
    at _abort (read-image-dicom-file-series.js:8:82347)
    at 0149037e
    at 0149037e
    at 0149037e
    at 0149037e
    at 0149037e
    at 0149037e
    at 0149037e
    at 0149037e
```
![image](https://github.com/Kitware/VolView/assets/116342733/5c29da4a-2507-4c05-ac4b-e2051ffcba9b)

Is this a know error ? Becuase I tested the same scenario sometime back.  Same error can be recreate  using sample data . 

If this is a duplicate error please link to the original.

**Comment by floryst** [comment]
What modality is the dataset that is failing to load?

**Comment by nUdawatte** [comment]
Hi , 

I tried with DICOM image files

**Comment by nUdawatte** [comment]
Hi , 
Please find the gdrive link for images .

https://drive.google.com/drive/folders/1tEnxDzHQABxHwrKDumLjDe_UbgNNa_a4

I first load image in CT folder and then add second image in PET

**Comment by PaulHax** [comment]
Got the files, thanks.  The CT and PET folders are loading for me on:
https://volview-dev.kitware.app/ and https://volview.kitware.app/ with
Chrome version 123
Firefox version 125

Here is another CT PET combo that might be interesting for you to try:
[https://volview-dev.kitware.app/?urls=[https://data.kitware.com/api/v1/file/63f39e907b0dfcc98f669cc6/download/joe-slim-pet-ct.zip]](https://volview-dev.kitware.app/?urls=%5Bhttps://data.kitware.com/api/v1/file/63f39e907b0dfcc98f669cc6/download/joe-slim-pet-ct.zip%5D)

**Comment by nUdawatte** [comment]
I can load them successfully but when you swich between the images I get errors. 

> https://volview-dev.kitware.app/?urls=[https://data.kitware.com/api/v1/file/63f39e907b0dfcc98f669cc6/download/joe-slim-pet-ct.zip]

This gives me following erros ( check the attached image) 

My crome version is **Version 124.0.6367.61 (Official Build) (32-bit)**


Anyhow it seems to be working on Firefox though . Even my local project 

![image](https://github.com/Kitware/VolView/assets/116342733/df1d572f-db43-4aa1-a762-c9a180c6f18a)

**Comment by PaulHax** [comment]
Thanks for checking things.  My guess is the `readImageDicomFileSeries` WASM code is running out of memory.  You could test with a debug build of `readImageDicomFileSeries` for a better error message if you like.  Could also try with 64 bit Chrome.

**Comment by nUdawatte** [comment]
@PaulHax 

>  Could also try with 64 bit Chrome.

Seems to be working on Chrome 64 bit as well.

**Comment by PaulHax** [comment]
Good to know.  Probably need 64 bit Chrome for these sized images.  Better error message would be nice but not trivial change.  Thanks for working through this.
