### ISSUE TITLE
Reset Views button not working

### ISSUE THREAD

**Issue by 1isten** [Kitware/VolView#591]
Using the latest main branch (at the time of opening this issue, the latest commit is [f25fb04](https://github.com/Kitware/VolView/commit/f25fb04c293e0df23ca5ecc05f13d5a688e91e36)),

the "Reset Views" button is not working:
<img width="71" alt="Screenshot 2024-05-12 at 3 52 27 PM" src="https://github.com/Kitware/VolView/assets/11518941/79d1298b-e408-4c94-ae9d-38e310db626a">

Nothing happens when clicked the button.

**Comment by PaulHax** [comment]
Looks like that button just got wired to reset the oblque views.
