### ISSUE TITLE
itk reader fail to detect image type ?

### ISSUE THREAD

**Issue by lchauvin** [Kitware/VolView#598]
Hello,

I updated VolView code to the latest (main branch), and I'm not able to load minc files now.

I did a bit of debugging, and the issue seems to be in the function `itkReader` in `src/io/readers.ts`.

Here the function `readImage` seems not able to load it. I tried to replace it with `mincReadImage` as a test, and it works.

It seems for some reason, `readImage` is not able to identify the image as minc, although, I checked the extension is supported.

When trying to read a minc image, I'm getting this error:

```
application/vnd.unknown.minc

loggers.ts:13 TypeError: Cannot read properties of undefined (reading '0')
    at readImage (@itk-wasm_image-io.js?v=9a3488c0:2031:30)
    at async itkReader (readers.ts:21:32)
    at async importSingleFile (importSingleFile.ts:31:22)
    at async invokeHandler (pipeline.ts:226:20
```

The error seems to happen here in `itk-wasm_image-io.js`:

```
  const readerWriter = image_io_index_default.get(io);
  const reader = readerWriter[0];
```

on the line `const reader = readerWriter[0];`

**Comment by lchauvin** [comment]
I tried with a Nifti image, and it works, but I don't see any difference, except for the file type:

```
application/vnd.unknown.nifti-1

File {name: 'MR_Gd.nii', lastModified: 1716909309256, lastModifiedDate: Tue May 28 2024 11:15:09 GMT-0400 (Eastern Daylight Time), webkitRelativePath: '', size: 4765024, …}
lastModified: 1716909309256
lastModifiedDate: Tue May 28 2024 11:15:09 GMT-0400 (Eastern Daylight Time) {}
name: "MR_Gd.nii"
size: 4765024
type: ""
webkitRelativePath: ""
[[Prototype]]: File
```

**Comment by PaulHax** [comment]
Nice find.  If you open an issue and offer to write a PR here: https://github.com/InsightSoftwareConsortium/itk-wasm might have a clean fix in a week or so.

**Comment by lchauvin** [comment]
Already did !! :)
