### ISSUE TITLE
nifti segmentation is not loading in axial plane 

### ISSUE THREAD

**Issue by naveensweth** [Kitware/VolView#602]
Hi,

I have created segmentations in the axial, coronal, and sagittal planes using the 3D Slicer tool and saved them in NIFTI format. However, when I try to load these segmentations, they do not display in the axial plane of VolView, although they do appear correctly in the coronal and sagittal planes.

Is there any setting I need to adjust to view the segmentation in the axial plane?

Note : This  issue with only nifti segmentation format.

![image](https://github.com/Kitware/VolView/assets/6927393/f2f8e458-00f1-4507-a495-28bbfbe9870d)

Best Regards

**Comment by PaulHax** [comment]
Maybe the default color map for "layers" does not show the axial segment value well.  "Add as layer" color map expects the image  to be a scan, not discreet values like in a segmentation.  

Try the "convert to segment group" menu option.  If no dice please share segmentation image.

**Comment by naveensweth** [comment]
I tried to upload NIfTI data here, but it is not supported.

When selecting "Axial Only" from Layouts, it shows the segmentation in the axial plane. However, when switching back to Quad View, it displays the segmentation in the axial plane, but it does not load by default.

**Comment by naveensweth** [comment]
Please let me know how to share the segmentation (.nii) data.

**Comment by PaulHax** [comment]
How did the "convert to segment group" menu button approach go?

To upload, put in a zip and cross fingers its under 25mb, then can attach to Github message.  Else, try Google Drive, Dropbox, etc.

**Comment by naveensweth** [comment]
[segFiletoVolView.zip](https://github.com/user-attachments/files/15782706/segFiletoVolView.zip)

**Comment by PaulHax** [comment]
Thinks look nominial to me.  Maybe a detailed step by step would help reproduce.

![image](https://github.com/Kitware/VolView/assets/16823231/5b134b1b-3e5b-4948-8233-45f9b058ae76)

**Comment by PaulHax** [comment]
Feel free to re-open
