### ISSUE TITLE
Question about FPP and TPP View Modes

### ISSUE THREAD

**Issue by vishwanathagqc** [Kitware/VolView#621]
Hello VolView Team,

I am wondering if there is any current support or ongoing development for First-Person Perspective (FPP) and Third-Person Perspective (TPP) view modes in VolView? 

These features would be incredibly useful for my current project where I need to navigate inside 3D volumes with more immersive controls. Specifically, I am looking for the ability to switch between a first-person perspective, where the view is from within the volume, and a third-person perspective, where the view follows the volume from an external point.

Is this something that is already available, or are there any plans to implement this in the near future?

Thank you for your time and assistance.

**Comment by floryst** [comment]
There isn't any current plans to support such views in VolView. That can be readily done with plain vtk.js, however. There's [first person flythrough controls](https://kitware.github.io/vtk-js/examples/MouseCameraTrackballFirstPersonManipulator.html) (with WASD and mouse) that can be used in a volume rendering scene.
