### ISSUE TITLE
Scooping Tool for Cropping Inside the Widget

### ISSUE THREAD

**Issue by vishwanathagqc** [Kitware/VolView#623]
Hello VolView Team,

I am interested in implementing a scooping tool that allows users to crop the inside of a 3D volume using an interactive widget. Specifically, I want to make the area inside the widget transparent or invisible, while keeping the outside visible.

Is there any existing implementation or ongoing development for such a feature in VolView? If not, could you provide guidance or suggestions on how this might be achieved using the current VolView framework?

Any help or pointers would be greatly appreciated.

Thank you for your time and assistance.

**Comment by vishwanathagqc** [comment]
I appreciate your response regarding the inverse cropping widget. 

To clarify my request : I need a smaller widget box inside the 3D volume that allows users to see a precise portion of the 3D volume. The current cropping tool in VolView does not support this level of precision.

Specifically, I am looking for a way to:
1. Place a smaller, adjustable widget box inside the 3D volume.
2. Make the area inside this smaller widget box invisible

**Comment by PaulHax** [comment]
Sound kewl.  
1. Brush up on that GLSL (teach me =)
2. checkout the vtk.js example and the cropping planes effect in the vtk.js codes
3. Ask in vtk.js discourse.
