### ISSUE TITLE
Incorrect rendering of DICOM SEG

### ISSUE THREAD

**Issue by fedorov** [Kitware/VolView#639]
See problematic sample below. You can download the DICOM study in question using the following:

```bash
$ pip install idc-index --upgrade
$ idc download 1.2.840.113654.2.55.192012426995727721871016249335309434385
```

https://volview.kitware.app/?urls=[s3://idc-open-data/46350591-eaf4-4f53-8790-645d72087aa2,s3://idc-open-data/3a84b4b8-b9c1-45e5-99db-d778fd5218f8,s3://idc-open-data/4c74c61b-48b1-48f4-af20-ac92b0a8a221,s3://idc-open-data/dc93f58c-2c3c-4dce-bed3-fdb291a40cee,s3://idc-open-data/9e7dc056-400c-4ac1-b01c-8e8441486f3c]

<img width="2060" alt="image" src="https://github.com/user-attachments/assets/3462fe2e-bea3-47ff-8537-e563b1b12d9d">

This is how it looks in OHIF v3:

https://viewer.imaging.datacommons.cancer.gov/v3/viewer/?StudyInstanceUIDs=1.2.840.113654.2.55.192012426995727721871016249335309434385&SeriesInstanceUIDs=1.2.840.113654.2.55.305538394446738410906709753576946604022,1.2.276.0.7230010.3.1.3.313263360.15787.1706310178.804490

<img width="2065" alt="image" src="https://github.com/user-attachments/assets/268a7685-2221-4c3c-a2e9-1b5d24642067">

And Slicer:

<img width="760" alt="image" src="https://github.com/user-attachments/assets/e7d3b6c8-041f-449a-9037-62b72eea6d1b">

**Comment by fedorov** [comment]
this is what I see if I open the CT series, and add SEG as a layer

<img width="2053" alt="image" src="https://github.com/user-attachments/assets/e35e0968-5a07-48ec-bbb0-ef1d4eeac5e6">

**Comment by floryst** [comment]
@PaulHax looks like the SEG layer is not being properly associated with the underlying image.

**Comment by PaulHax** [comment]
Thank for the files!  For the SEG file, our WASM loader computes incorrect spacing.  Also, the pixel array looks like each frame along the axial has a single segment, rather than merging multple segments together for each frame.  Just the tip of the issues probably.

**Comment by jadh4v** [comment]
The ITK-Wasm PR https://github.com/InsightSoftwareConsortium/ITK-Wasm/pull/1165 was recently merged. The `@itk-wasm/dicom` package was released (https://www.npmjs.com/package/@itk-wasm/dicom/v/7.2.0). I will test out the new reader in Volview. Hopefully its easily swappable/upgradable.

**Comment by floryst** [comment]
I'll update that deployment this week. I'm targeting EOD Wednesday.

**Comment by floryst** [comment]
@fedorov I forgot to mention that volview.kitware.app is now updated to the latest dev version!

**Comment by fedorov** [comment]
@floryst it is working now, thank you! 

One observation is that SEG thumbnails give infinite spinner - maybe you should just disable rendering of thumbnails for SEG series?

<img width="436" alt="image" src="https://github.com/user-attachments/assets/e55c8790-0c8f-4052-855e-085e2ed8616c">
