### ISSUE TITLE
Easiest way to get the world coordinate out of a clicked location for debugging

### ISSUE THREAD

**Issue by sedghi** [Kitware/VolView#644]
Two questions:

- How can I efficiently (easily) obtain a world coordinate from clicking on a viewport for debugging purposes?
- What's the simplest method to retrieve the actor and mapper for each viewport? is there any utilities on window similar to vtk examples?

![CleanShot 2024-08-20 at 12 03 50@2x](https://github.com/user-attachments/assets/def266e6-f5d1-4c8e-8e29-2fb8d656ecb8)

Thanks!

**Comment by PaulHax** [comment]
> How can I efficiently (easily) obtain a world coordinate from clicking on a viewport for debugging purposes?

console.log here? https://github.com/Kitware/VolView/blob/main/src/vtk/RulerWidget/behavior.ts#L92

> What's the simplest method to retrieve the actor and mapper for each viewport? is there any utilities on window similar to vtk examples?

Tricker.  Here is a spot where to can get the "slice" actor/mapper pair associated with a "view":
https://github.com/Kitware/VolView/blob/main/src/components/vtk/VtkBaseSliceRepresentation.vue#L36
