### ISSUE TITLE
Unsupported data type error

### ISSUE THREAD

**Issue by Srujith20** [Kitware/VolView#655]
Issue Resolved

**Comment by floryst** [comment]
I think there's an issue with itk-wasm opening `nii.gz` files. If you decompress them into `.nii` files, do they load?

**Comment by PaulHax** [comment]
Yes, we lost the compressed `nii.gz` format support somewhere.  

After decompressing, itk-wasm returns a  `BigInt64Array` typed array, which looks like we don't handle well.  @Srujith20 Try converting the label map file to a Int32 typed array.

**Comment by Srujith20** [comment]
> Yes, we lost the compressed `nii.gz` format support somewhere.
> 
> After decompressing, itk-wasm returns a `BigInt64Array` typed array, which looks like we don't handle well. @Srujith20 Try converting the label map file to a Int32 typed array.

I am encountering the following error when I try to visualize an Int32 typed array.
<img width="839" alt="Screenshot 2024-10-01 at 12 10 14 PM" src="https://github.com/user-attachments/assets/ec5b2c2d-2868-4021-8baf-ca55ac0cd688">

**Comment by Srujith20** [comment]
> I think there's an issue with itk-wasm opening `nii.gz` files. If you decompress them into `.nii` files, do they load?

I am still not able to load the label after decompressing. When I try to visualize the image it opens up sometimes and sometimes it throws the "could not load" error.

**Comment by PaulHax** [comment]
The loader still thinks its a Int64 image.  Check your image conversion code.  For more help here:
- Suggest using ITK's Python API.  
- Post the python code you use to do the conversion
- Post the `print(converted_image)` result
- Share the before and after image here.
