### ISSUE TITLE
readOverlappingSegmentation not found on itk-wasm

### ISSUE THREAD

**Issue by lchauvin** [Kitware/VolView#659]
Hello,

I updated the code to the latest version, and re-install `itk-wasm` to be sure, but I'm having this error on the console when going to Volview:

`Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@itk-wasm_dicom.js?v=34dba275' does not provide an export named 'readOverlappingSegmentation' (at dicom.ts:6:3)`

preventing volview to load. No error during build and `npm run dev`.

I don't know if it's related, but I'm on Mac, so I need to force npm version to v20.17 (otherwise some packages can't be found).

But my `itk-wasm` version is 

```
"name": "itk-wasm",
"version": "1.0.0-b.178",
```

**Comment by PaulHax** [comment]
We updated the @itk-wasm/dicom package too.  Maybe nuke node_modules and `npm install` to be safe.

**Comment by lchauvin** [comment]
I tried to nuke `node_modules/itk-wasm` and re-run `npm install` but it didn't work.

However, I just tried to nuke completely `node_modules` and re-rerun `npm install` and it worked.

Thanks :)
