### ISSUE TITLE
console error in the official volview site

### ISSUE THREAD

**Issue by 1isten** [Kitware/VolView#661]
open or refresh https://volview.kitware.app/ 

an error shows in the console: 
```
Could not read the input DICOM file
```

![image](https://github.com/user-attachments/assets/4d58c317-8420-4c8c-9a96-98a1d711bdfb)

**Comment by 1isten** [comment]
seems Google Chrome doesn't have this error.

The error happens in my Edge Browser
```
Browser: Microsoft Edge v129.0.2792.89 (64-bit)
OS: Windows 11 (23H2)
```

**Comment by floryst** [comment]
That first error message is harmless, as it stems from a workaround for pre-loading WASM resources. We haven't revisited preloading WASM resources without triggering that error message yet.

Closing, unless the error actually is breaking something.
