### ISSUE TITLE
*.gz file extension failed to resolve to correct mime type

### ISSUE THREAD

**Issue by 1isten** [Kitware/VolView#663]
For example, when drag'n'drop a `file.nii.gz` compressed nifti file into the volview website, it cannot be opened.
![image](https://github.com/user-attachments/assets/98685e07-adf1-4f58-bce1-606f6604bd04)

I added some debug console log and see the `fileType` is being resolved to `application/gzip`, which is incorrect.
![image](https://github.com/user-attachments/assets/4d7cfc1b-224d-427d-858c-2acbce4a6821)
By looking up the `mimeTypes.ts` file I think it should be `application/vnd.unknown.nifti-1`.

I think the `*.gz` file names should be handled specifically in the `updateFileMimeType.ts` to correctly resolve the mime type.

Below is my quick fix for the `nii.gz` file:
![image](https://github.com/user-attachments/assets/c92a3019-eeba-4ca2-afb9-0b670b5f85c2)

My implementation is not very comprehensive. Hope this can be fixed by volview offical team, thanks!

**Comment by floryst** [comment]
Thanks! You do have the right idea here. I've linked a PR to fix this issue.
