### ISSUE TITLE
Source maps are broken for .vue files

### ISSUE THREAD

**Issue by cjh1** [Kitware/VolView#77]
Seems it was broken by this update: 9024d9e2213e77a3c9b2f797be29acfb6c58b147

**Comment by floryst** [comment]
Have you tried re-running npm install? I had also run into this, but now it's working for me, and I'm guessing that it was because of an npm install.

**Comment by cjh1** [comment]
Yup, I have tried to reinstall.

**Comment by cjh1** [comment]
I tried the patch version bump, but still not joy. I tried removing node_modules. You don't see the issue if you remove node_modules and reinstall?

**Comment by cjh1** [comment]
I tried bumping various versions and changing the sourcemap type, but neither seemed to help.

**Comment by floryst** [comment]
I think this may be an issue with typescript + vue-cli@5. Not entirely sure just yet.

**Comment by PaulHax** [comment]
This is no longer an issue.
